"""Demand Forecast API Router."""
from uuid import UUID
from typing import Optional
from fastapi import APIRouter, Depends, Query, status
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.api.deps import (
    require_permission,
    require_facility_scope,
)
from app.models.user import User
from app.schemas.fl import FacilityForecastResponse
from app.services.fl_service import FlService

router = APIRouter(prefix="/forecast", tags=["Demand Forecasting"])


@router.get(
    "/facility/{facility_id}",
    response_model=FacilityForecastResponse,
    status_code=status.HTTP_200_OK,
    summary="Get latest 7-day demand forecasts for a facility",
)
def get_facility_forecast(
    facility_id: UUID,
    days: int = Query(7, ge=1, le=30, description="Forecast horizon in days"),
    current_user: User = Depends(require_permission("view_phc_forecast")),
    scoped_user: User = Depends(require_facility_scope),
    db: Session = Depends(get_db),
):
    """Retrieve 7-day medicine demand forecasts generated by the active federated model."""
    return FlService.get_facility_forecast(db=db, facility_id=facility_id, drug_id=None, days=days)


@router.get(
    "/facility/{facility_id}/drug/{drug_id}",
    response_model=FacilityForecastResponse,
    status_code=status.HTTP_200_OK,
    summary="Get demand forecast for a specific drug at a facility",
)
def get_facility_drug_forecast(
    facility_id: UUID,
    drug_id: UUID,
    days: int = Query(7, ge=1, le=30, description="Forecast horizon in days"),
    current_user: User = Depends(require_permission("view_phc_forecast")),
    scoped_user: User = Depends(require_facility_scope),
    db: Session = Depends(get_db),
):
    """Retrieve medicine demand forecast for a single drug at a facility."""
    return FlService.get_facility_forecast(db=db, facility_id=facility_id, drug_id=drug_id, days=days)
